import assert from 'node:assert/strict';
import test from 'node:test';

import './documentation-surfaces.spec.mjs';
import {
  auditChangeEvidence,
  auditDocumentation,
  renderArchitectureDiagram,
  shouldAuditWorkspace,
} from './documentation-integrity.mjs';

function baseFiles(overrides = {}) {
  return new Map(
    Object.entries({
      'package.json': JSON.stringify({ scripts: { check: 'echo check' } }),
      'README.md':
        '# SteadyStack\n\nSee [browser auth](docs/browser-authentication.md).\n',
      'docs/browser-authentication.md': [
        '# Browser authentication',
        '`NEXT_PUBLIC_AUTHENTICATION_PROFILE` supports `development`, `oidc`, `session`, and `none`.',
        'The credential endpoint is same-origin and tokens stay in memory.',
      ].join('\n'),
      'docs/oidc-authentication.md': [
        '# OIDC authentication',
        '`AUTH_ACCESS_TOKEN_VERIFIER=development|oidc`',
        '`AUTH_OIDC_ISSUER`',
        '`AUTH_OIDC_AUDIENCE`',
        '`identity_provider_unavailable`',
        '`invalid_access_token`',
      ].join('\n'),
      '.env.example': [
        'NEXT_PUBLIC_AUTHENTICATION_PROFILE=development',
        'AUTH_ACCESS_TOKEN_VERIFIER=development',
        'AUTH_OIDC_ISSUER=',
        'AUTH_OIDC_AUDIENCE=',
      ].join('\n'),
      ...overrides,
    }).map(([file, content]) => [file, { content }]),
  );
}

const graph = {
  nodes: {
    api: {
      name: 'api',
      data: {
        root: 'apps/api',
        tags: ['scope:backend'],
        targets: { test: {} },
      },
    },
  },
  dependencies: { api: [] },
};

function audit(overrides = {}) {
  const files = baseFiles(overrides.files);
  return auditDocumentation({
    files,
    packageJson: { scripts: { check: 'echo check' } },
    graph,
    changeEvidence: overrides.changeEvidence ?? [],
  });
}

test('reports broken internal links and referenced files', () => {
  const failures = audit({
    files: {
      'docs/example.md': [
        '# Example',
        '[missing](missing.md)',
        'Run `tools/missing-script.mjs`.',
      ].join('\n'),
    },
  });

  assert(failures.some((failure) => failure.includes('broken internal link')));
  assert(
    failures.some((failure) =>
      failure.includes('missing referenced repository path'),
    ),
  );
});

test('reports unknown package scripts and Nx targets', () => {
  const failures = audit({
    files: {
      'docs/commands.md': [
        '# Commands',
        '```bash',
        'pnpm missing-script',
        'pnpm nx run api:missing',
        '```',
      ].join('\n'),
    },
  });

  assert(
    failures.some((failure) => failure.includes('unknown root package script')),
  );
  assert(failures.some((failure) => failure.includes('unknown Nx target')));
});

test('reports unknown documented environment variables', () => {
  const failures = audit({
    files: {
      'docs/environment.md': [
        '# Environment',
        '```dotenv',
        'AUTH_MISSPELLED_SETTING=true',
        '```',
      ].join('\n'),
    },
  });

  assert(
    failures.some((failure) => failure.includes('AUTH_MISSPELLED_SETTING')),
  );
});

test('reports stale identity outside the historical allowlist', () => {
  const failures = audit({
    files: {
      'docs/current.md': 'Install `@agentic-webapp/workspace-plugin`.',
      'docs/steadystack-migration.md':
        'Historical `@agentic-webapp/workspace-plugin`.',
    },
  });

  assert.equal(
    failures.filter((failure) =>
      failure.includes('legacy pre-SteadyStack identity'),
    ).length,
    1,
  );
});

test('renders a stable sorted Nx project graph', () => {
  const diagram = renderArchitectureDiagram({
    nodes: {
      web: {
        name: 'web',
        data: {
          root: 'apps/web',
          tags: ['runtime:browser', 'scope:web'],
        },
      },
      api: {
        name: 'api',
        data: {
          root: 'apps/api',
          tags: ['runtime:node', 'scope:backend'],
        },
      },
    },
    dependencies: {
      web: [{ source: 'web', target: 'api', type: 'dynamic' }],
      api: [],
    },
  });

  assert(
    diagram.indexOf('api<br/>apps/api') < diagram.indexOf('web<br/>apps/web'),
  );
  assert.match(diagram, /project_web -->\|dynamic\| project_api/);
  assert.match(diagram, /Generated by `pnpm docs:architecture`/);
});

test('requires roadmap and ADR evidence for generator changes', () => {
  const changes = [
    {
      status: 'M',
      file: 'tools/workspace-plugin/src/generators/domain/generator.ts',
    },
  ];
  assert.deepEqual(auditChangeEvidence({ changes }), [
    'generator or architecture changes require docs/TODO.md',
    'generator or architecture changes require a docs/adr/*.md update',
  ]);

  changes.push(
    { status: 'M', file: 'docs/TODO.md' },
    { status: 'A', file: 'docs/adr/0018-documentation-integrity.md' },
  );
  assert.deepEqual(auditChangeEvidence({ changes }), []);
});

test('requires roadmap and ADR evidence for boundary changes', () => {
  const changes = [
    { status: 'M', file: 'packages/example/project.json' },
    { status: 'M', file: 'docs/TODO.md' },
  ];
  assert.deepEqual(
    auditChangeEvidence({
      changes,
      boundaryChanges: new Set(['packages/example/project.json']),
    }),
    ['generator or architecture changes require a docs/adr/*.md update'],
  );
});

test('runs repository-specific checks only in the upstream template', () => {
  assert.equal(shouldAuditWorkspace({ name: '@steadystack/source' }), true);
  assert.equal(shouldAuditWorkspace({ name: '@product/example' }), false);
});
